[build]
builder = "RAILPACK"

[build.env]
NEXT_TELEMETRY_DISABLED = "1"
SKIP_ENV_VALIDATION = "true"
NPM_CONFIG_LEGACY_PEER_DEPS = "true"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
